name: Escaneo con Gitleaks


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Escanear con Gitleaks
        uses: zricethezav/gitleaks-action@v2.2.0
