name: Escaneo con Gitleaks

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  escaneo-gitleaks:
    name: Ejecutar Gitleaks para detectar secretos
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v3

      - name: Instalar Gitleaks
        run: |
          curl -sSL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64 -o gitleaks
          chmod +x gitleaks
          sudo mv gitleaks /usr/local/bin/

      - name: Ejecutar análisis con Gitleaks
        run: gitleaks detect --source=. --verbose --redact
